version: '3.7'

services:

  django:
    container_name: caregivers-django
    build:
      context: ./backend/
    environment:
      - APP_ENV=production
      - DB_NAME=caregivers
      - DB_USERNAME=caregivers
      - DB_PASSWORD=caregivers
      - DB_HOSTNAME=postgres
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
      - EMAIL_HOST_USER=example@example.com
      - EMAIL_HOST_PASSWORD=xxxxxxxxxxxxxxxx
      - CORS_ALLOWED_ORIGIN=http://localhost
      - ALLOWED_HOST=localhost
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend/scripts:/app/scripts/
      - ./backend/requirements:/app/requirements
      - ./backend/src:/app/src/
    restart: always

  postgres:
    container_name: caregivers-postgres
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=caregivers
      - POSTGRES_USER=caregivers
      - POSTGRES_DB=caregivers
    volumes:
      - caregivers-postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: caregivers-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - caregivers-pgadmin-data:/var/lib/pgadmin
    restart: always

  nextjs:
    container_name: caregivers-nextjs
    ports:
      - "80:3000"
    build:
      context: ./frontend
    environment:
      - BASE_URL=http://localhost:3000
      - STATIC_DIR=/
      - API_URL=http://localhost:8000/api/v1
    restart: always

volumes:
  caregivers-postgres-data:
  caregivers-pgadmin-data:
