# Generated by Django 4.1.2 on 2023-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donationcompany_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('-is_active', '-created'), 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(help_text='Recommended image resolution is 1920×1080 (HD) or higher.', null=True, upload_to='images/donations/donation', verbose_name='cover image'),
        ),
    ]
