# Generated by Django 4.1.2 on 2023-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(help_text='Recommended image resolution is 1920×1080 (HD) or higher.', null=True, upload_to='images/blogs/blog', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], max_length=100, null=True, verbose_name='media type'),
        ),
    ]
