name: CI
on:
  push:
    branches:
      - main
jobs:
  Main_branch:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Building backend docker image
        run: docker build ./backend/ -t codeforacause/website-horizont-center:${{ github.run_number }}
      - name: Building frontend docker image
        run: docker build ./frontend/ -t codeforacause/website-horizont-center:${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pushing docker image to CR
        run: docker push codeforacause/website-horizont-center:${{ github.run_number }}
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/docker-compose.website-horizont-center.yaml"]'
        env:
          TAG_NUMBER: "${{ github.run_number }}"
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./docker-compose.website-horizont-center.yaml"
          target: "./Projects/website-horizont-center/"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd ./Projects/website-horizont-center/ && docker-compose -f docker-compose.website-horizont-center.yaml up -d
